export const SIGN_UP = "SIGN_UP";
export const AUTH_ERROR = "AUTH_ERROR";
export const SIGN_IN = "SIGN_IN";
export const USER_LOADED = "USER_LOADED";
export const SIGN_OUT = "SIGN_OUT";
export const GET_TRANSACTIONS = "GET_TRANSACTIONS";
export const SEARCH_TRANSACTIONS = "SEARCH_TRANSACTIONS";
export const GET_TRANSACTION = "GET_TRANSACTION";
export const CREATE_SUBSCRIPTION = "CREATE_SUBSCRIPTION";
export const UPLOAD_IMAGE = "UPLOAD_IMAGE";
/**Plans */
export const GET_TOTAL = "GET_TOTAL";
export const GET_DASHBOARD_PLANS = "GET_DASHBOARD_PLANS";
export const GET_ALLPLANS = "GET_ALLPLANS";
export const EDIT_PLAN = "EDIT_PLAN";
export const CREATE_PLAN = "CREATE_PLAN";
export const GET_PLAN = "GET_PLAN";
export const DELETE_PLAN = "DELETE_PLAN";
export const GET_SUBSCRIPTION = "GET_SUBSCRIPTION";

/**payments */
export const MAKE_PAYMENT = "MAKE_PAYMENT";
export const GET_PAYMENT_PLAN = "GET_PAYMENT_PLAN";
export const ACTIVATE_SUBSCRIPTION = "ACTIVATE_SUBSCRIPTION";
export const CANCEL_SUBSCRIPTION = "CANCEL_SUBSCRIPTION";
export const UPDATE_SUBSCRIPTION = "UPDATE_SUBSCRIPTION";
export const CONFIRM_PAYMENT = "CONFIRM_PAYMENT";

/**transactions */
export const GET_DASHBOARD_TRANSACTIONS = "GET_DASHBOARD_TRANSACTIONS";
